hifis-net/ansible-role-rsd

.github/dependabot.yml
=> fixes(#4): added dependabot.yml

.github/workflows/prepare-action/action.yml, meta/main.yml, poetry.lock, pyproject.toml
* bump python version to `3.10`
* upgrade dependencies ansible and ansible-lint
=> Upgrade python to 3.10

.github_changelog_generator, CHANGELOG.md
=> Add params file for github-changelog-generator

.github/workflows/ci.yml, README.md, molecule/default/molecule.yml
=> Run molecule test against Ubuntu 22.04

README.md, defaults/main.yml, tasks/check.yml, tasks/install.yml, tasks/main.yml
=> Add preflight checks

molecule/default/converge.yml, molecule/default/molecule.yml, tasks/check.yml, tasks/install.yml
* Determine if the first role execution is running in check-mode ("initial dry-run")
* skip some tasks in the initial dry-run that would otherwise fail
=> Test initial dry-run with molecule

README.md, defaults/main.yml, templates/docker-compose.yml.j2
* add a variable to be able to change the container registry path from where RSD images are pulled
Closes #35
=> Make container registry configurable

LICENSE.md
* add a line break between copyright lines
=> Licens File Formatting

CHANGELOG.md, CHANGELOG.md.license, HISTORY.md, HISTORY.md.license, VERSION, pyproject.toml
=> Prepare release v1.0.0

templates/docker-compose.yml.j2
To be in sync with https://github.com/research-software-directory/RSD-as-a-service/blob/main/deployment/docker-compose.yml
=> Add restart policy to docker-compose.yml template

handlers/main.yml, tasks/install.yml
=> Add handler to recreate containers on .env file changes

CITATION.cff
=> Add citation metadata

README.md, handlers/main.yml, tasks/check.yml, tasks/install.yml
=> Always pull container images in case of using image tag 'latest'

README.md, defaults/main.yml, templates/rsd-secrets.env.j2
=> Integrate matomo support

README.md, defaults/main.yml, handlers/main.yml, tasks/install.yml, templates/docker-compose.yml.j2, templates/rsd-secrets.env.j2
=> Enable compose project names

README.md, tasks/check.yml, tasks/install.yml
=> Fix: Docker Compose validation on systems with Docker Compose CLI plugin

.github_changelog_generator, CHANGELOG.md, CITATION.cff, VERSION, pyproject.toml
* Closes https://github.com/hifis-net/ansible-role-rsd/milestone/6
=> Prepare release v1.4.0

.github/workflows/ci.yml, defaults/main.yml, molecule/default/prepare.yml, requirements.yml, tasks/check.yml
* community.docker `v3.2.1` ([CHANGELOG](https://github.com/ansible-collections/community.docker/blob/3.2.1/CHANGELOG.rst))
* geerlingguy.docker `6.0.4` ([Release Notes](https://github.com/geerlingguy/ansible-role-docker/releases/tag/6.0.4))
* geerlingguy.pip `2.2.0` ([Release Notes](https://github.com/geerlingguy/ansible-role-pip/releases/tag/2.2.0))
=> Bump all Ansible requirements and make required changes

README.md, defaults/main.yml, templates/docker-compose.yml.j2, templates/rsd-secrets.env.j2
Introduce new env variables:
- `rsd_postgres_db_host`
- `rsd_postgres_db_host_port`
- `rsd_postgres_db`
- `rsd_postgres_user`
* Closes #129
=> Add environment variables to change database connection

README.md, defaults/main.yml, templates/docker-compose.yml.j2, templates/nginx.conf.j2, templates/rsd-secrets.env.j2
=> Add env var to enable oaipmh scraper
